version: "1"

run:
  tests: true
  timeout: 5m

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - staticcheck
    - unused
    - revive
    - errcheck
    - deadcode
    - gocritic
    - gosimple
    - typecheck
    - ineffassign
