name: Bug Report
description: Report a bug with steps to reproduce, expected vs. actual behavior.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue step-by-step.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Screenshots, logs, environment details, etc.
