name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --remote --recursive --force

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.4

      - name: Verify Go installation
        run: |
          echo "GOROOT: ${{ env.GOROOT }}"
          ls ${{ env.GOROOT }}/src/database/sql
          go version

      - name: Run unit tests
        run: go test -v ./tests/unit/...

      - name: Run integration tests
        run: go test -v ./tests/integration/...